version: "3.8"

services:
  redis:
    image: redis:alpine
    networks:
      - back-tier
    healthcheck:
      test: /healthchecks/redis.sh

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: 5s
    networks:
      - back-tier
    ports:
      - "5432:5432"

  vote:
    build: ./vote
    ports:
      - "5002:80"
    depends_on:
      - redis
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    ports:
      - "5001:80"
      - "127.0.0.1:9229:9229"
    depends_on:
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./worker
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:

volumes:
  db-data:


